### ISSUE TITLE
Strange issues with imagestreams being overwritten on ocp and ocp4

### ISSUE THREAD

**Issue by HumairAK** [AICoE/aicoe-cd#230]
This has resulted in us having to ignore imagestream fields for certain apps, see #229 

We should figure out what is going wrong here and then revert these changes (we should avoid using ignoredifferences as much as possible).

**Comment by anishasthana** [comment]
cc @harshad16 @tumido

**Comment by tumido** [comment]
cc @martinpovolny

**Comment by harshad16** [comment]
Similar issue reference: https://github.com/thoth-station/thoth-application/issues/779

**Comment by harshad16** [comment]
After rechecking on this, the image ignores issues seem to be happening from ArgoCD side. 

**Issue**: 
On apply of the components like cronjob/deployments, a full absolute path of imagestream is being referenced as an image.
 ```
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: example
spec:
  ...
     image: > quay.io/foo/example@sha256:9adba73d50bd1f4dfabdc3dfc85e3517264ca80e45197839c11c0290419cb19c
```

instead of 
 ```
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: example
spec:
  ...
     image: example
```

However, this behavior should not occur. as the processing of imagestream path happens in child process like a job(from a cronjob), pod(from deployment).   

**Details**:

This is happening when argocd is deploying applications with cronjobs and deployments. 
As the same application manually deployed on the openshift doesn't show the same transitions.
