### ISSUE TITLE
document some labeling good practice

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-cd#29]
I have stated using a set of commonLabels with all the kustomize files:

```
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: kebechet
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
```

ArgoCD itself is adding `app.kubernetes.io/instance=test-thoth-kebechet` depending on the ArgoCD application created.

I would like to standardize on the usage of `managed-by`: shall we make it the rover group of the team responsible for the management/operation of the app and append `-argocd` if managed via ArgoCD or `-manual` if we do it manually using kustomize...
